### ISSUE TITLE
[Bug] Pause button blocks access to last item in download queue

### ISSUE THREAD

**Issue by peskdale** [LunaTools/LunaSea#209]
**Describe the Bug**
Green pause button in bottom-right of download screen blocks access to the menu for the last item in the download queue. Scrolling does not bring the last item high enough to be able to interact with it.

**To Reproduce**
Add enough items to the download queue such that it fills the screen. Attempt it interact with the last item.

**Screenshots**
(Filenames removed for privacy)
![image](https://user-images.githubusercontent.com/5855217/81397517-63a51b80-911f-11ea-9df3-1d4814f767ce.png)

**Versions**
LunaSea 2.2.0, iOS 13.4.1 on iPhone 7

**Additional context**
Tested with SABnzbd per screenshot, but presumably affects other download clients too.
This might be a device-specific issue - I know the iPhone 7 has a relatively small screen size 
(but it is the same as the new SE model).

**Comment by JagandeepBrar** [comment]
Thanks for the bug report!

This occurs on all platforms, so it isn’t a size-specific problem. I will be changing how the queue in the near future, which will resolve this problem.

**Comment by JagandeepBrar** [comment]
I have just pushed a change to the branch `v3.1.0` which will now cause the FAB to hide on a downwards scroll action, and reappear when scroll back up. This scroll action will work even when the list doesn't fill up the entire view. Will be live in the first TestFlight for v3.1.0!

https://github.com/LunaTools/LunaSea/commit/b77bbbb96543201db51b42d70068ab76481aa396
