### ISSUE TITLE
[Bug] Special characters in basic auth don't work

### ISSUE THREAD

**Issue by flying-sausages** [LunaTools/LunaSea#215]
**Describe the Bug**
A password with `@` will not work for the current basic auth implementation

**To Reproduce**
Set up a reverse proxy which allows through a password with an `@` in it 

**Expected Behaviour**
Log in

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Versions**
2.2.0

**Additional context**
https://www.ietf.org/rfc/rfc3986.txt
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

It would be nice to have a more complex authentication dialogue, and take the basic auth credentials there. This way you can encode them properly and send them as headers

**Comment by flying-sausages** [comment]
Substituting for `%40` doesn't seem to work

**Comment by JagandeepBrar** [comment]
This has been remedied in the most recently TestFlight for 2.3.0 (220003) which gives users the option to define custom headers, including creating a basic authentication/`Authorization` header. Integrated is even the ability to encode it to base64 for you!
